sudo: required
services:
  - docker

before_install:
  - docker build -t uknadkarni/docker-react -f Dockerfile.dev .
  
script:
  - docker run uknadkarni/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-281002093962"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access-key-id
  secret_access_key:
    secure: "$secret-access-key"
